// Built-in example programs ("factory presets"). Served read-only in the
// sidebar's SAMPLES section (never written to disk) and shown on Quick Start.

import type { ProgramHelp } from './programHelp'

export interface Sample {
  name: string
  description: string
  code: string
  // Optional "operator's manual" (ⓘ INFO / right-click in the Console).
  help?: ProgramHelp
}

export const SAMPLES: Sample[] = [
  {
    name: 'DEMON',
    description:
      'The Dancing Demon — a pixel-exact trace of the genuine 1979 TRS-80 imp, tap-dancing to "Aint She Sweet" on a curtained stage. Captured from the real program and redrawn at full resolution.',
    help: {
      about:
        'A pixel-for-pixel trace of the 1979 Dancing Demon: the figure was captured straight out of the real TRS-80 program running in our emulator, then redrawn here at full 128x48 resolution with SET. The horns, the sly slanted eyes, the splayed feet and every dance pose are the genuine ones.',
      play: [
        'Press RUN: the curtains rise, the band strikes up "Ain\'t She Sweet," and the demon taps.',
        'Click or press a key once so the speaker icon turns green to hear the tune through the app audio.',
        'The dance cycles five real captured poses: home, a right kick, a left kick, arms raised overhead, and a wild crossed-leg kick.'
      ],
      hints: [
        'The five dance poses live in the DATA at 7000+ — each is a 30x30 bitmap traced from the original. Edit the # marks to change a pose.',
        'The routine is the DATA at 8100: sixteen pose numbers (0-4). Re-order them to choreograph your own dance.',
        'The tune is the PLAY string on line 85 (note notation). Faster dance: lower the PAUSE on line 120. Faster music: raise the T value on line 85.',
        'The title font is the DATA at 8000 (letters of DANCIGEMO); the demon is drawn 1:1 by the loop at 500.'
      ]
    },
    code: [
      '10 REM ---- THE DANCING DEMON (TRACED FROM THE 1979 ORIGINAL) ----',
      '20 DIM SP$(4, 29), FN$(8, 4), MV(15)',
      '30 FOR P = 0 TO 4 : FOR R = 0 TO 29 : READ SP$(P, R) : NEXT R : NEXT P',
      '40 FOR T = 0 TO 8 : FOR R = 0 TO 4 : READ FN$(T, R) : NEXT R : NEXT T',
      '50 FOR M = 0 TO 15 : READ MV(M) : NEXT M',
      '60 KEY$ = "DANCIGEMO" : BX = 49 : BY = 15',
      '70 GOSUB 200 : REM curtain raise',
      '80 REM "Aint She Sweet" - phrase endings climb chromatically (G G# A B C)',
      '85 PLAY "MB T210 O4 L8 E F+ G4 G P8 F G G+4 G+ P8 F+ G+ A4 A P8 G A B4 > C4 < P8 E F+ G4 G P8 F G G+4 G+ P8 F+ G+ A4 A P8 G A B4 > C2"',
      '90 FOR PS = 1 TO 4',
      '100   FOR M = 0 TO 15',
      '110     CF = MV(M)',
      '120     CLS : GOSUB 300 : GOSUB 500 : PAUSE 80',
      '130   NEXT M',
      '140 NEXT PS',
      '150 CF = 0 : CLS : GOSUB 300 : GOSUB 500 : END',
      '200 REM ---- curtain raise ----',
      '210 FOR W = 60 TO 2 STEP -4',
      '220   CLS : GOSUB 400 : CW = W : GOSUB 450 : PAUSE 55',
      '230 NEXT W',
      '240 RETURN',
      '300 REM ---- full scene ----',
      '310 GOSUB 400 : CW = 2 : GOSUB 450 : GOSUB 900 : RETURN',
      '400 FOR X = 0 TO 127 : SET(X, 0) : NEXT X',
      '410 FOR X = 4 TO 123 : SET(X, 45) : NEXT X',
      '420 RETURN',
      '450 REM ---- pleated curtains, width CW ----',
      '460 FOR Y = 1 TO 44',
      '470   FOR X = 0 TO CW : IF X - INT(X / 2) * 2 = 0 THEN SET(X, Y)',
      '480   NEXT X',
      '490   FOR X = 127 - CW TO 127 : IF X - INT(X / 2) * 2 = 0 THEN SET(X, Y)',
      '495   NEXT X',
      '498 NEXT Y',
      '499 RETURN',
      '500 REM ---- draw demon pose CF at BX,BY (1x, traced) ----',
      '510 FOR R = 0 TO 29 : L$ = SP$(CF, R) : Y = BY + R',
      '520   FOR C = 1 TO 30 : IF MID$(L$, C, 1) = "#" THEN SET(BX + C - 1, Y)',
      '530   NEXT C',
      '540 NEXT R',
      '550 RETURN',
      '900 T$ = "DANCING DEMON" : TX = 31',
      '910 FOR I = 1 TO LEN(T$)',
      '920   CH$ = MID$(T$, I, 1)',
      '930   IF CH$ = " " THEN TX = TX + 5 : GOTO 995',
      '940   LI = INSTR(KEY$, CH$) - 1',
      '950   FOR R = 0 TO 4 : G$ = FN$(LI, R)',
      '960     FOR C = 1 TO LEN(G$) : IF MID$(G$, C, 1) = "#" THEN SET(TX + C, 1 + R)',
      '970     NEXT C',
      '980   NEXT R',
      '990   TX = TX + 5',
      '995 NEXT I',
      '998 RETURN',
      '7000 DATA "..............................", ".....###..............###.....", ".......###..........###......."',
      '7005 DATA "......##################......", ".....####################.....", "....######################...."',
      '7010 DATA "...####..##..####..##..####...", "...####......####......####...", "....######################...."',
      '7015 DATA "......##################......", "........##############........", "..........##########.........."',
      '7020 DATA "............######............", "...........########...........", ".........############........."',
      '7025 DATA ".......###..######..###.......", "......##...########...##......", ".....###..##########..###....."',
      '7030 DATA "...######.##########.######...", "...#####...########...#####...", "............##...##..........."',
      '7035 DATA "............##....##..........", "............##.....##.........", "............##......##........"',
      '7040 DATA "............##.....##.........", "............##....##..........", "............##..###..........."',
      '7045 DATA "...........###...###..........", ".........####.....######......", ".....#######.................."',
      '7050 DATA "..............................", "........###............##.....", "..........###........###......"',
      '7055 DATA "........################......", "......###################.....", ".....#####################...."',
      '7060 DATA "....######.##...###.##..###...", "....######......###.....###...", ".....#####################...."',
      '7065 DATA ".......##################.....", ".........##############.......", "...........##########........#"',
      '7070 DATA ".............######.........##", "............#########.....#.##", "..........############....####"',
      '7075 DATA "........###..######..##...##..", ".......##...########..##.##...", "......##...##########..###...."',
      '7080 DATA ".....##....##########.........", "....###.....########..........", "...#####....##...##..........."',
      '7085 DATA "....####...##....##...........", ".....##...##.....##...........", "......#..##......##..........."',
      '7090 DATA "..........##.....##...........", "...........##....##...........", "............###..##..........."',
      '7095 DATA "...........###...###..........", ".......######.....####........", "...................#######...."',
      '7100 DATA "..............................", "......##............###.......", ".......###........###........."',
      '7105 DATA ".......################.......", "......###################.....", ".....#####################...."',
      '7110 DATA "....###..##.###...##.######...", "....###.....###......######...", ".....#####################...."',
      '7115 DATA "......##################......", "........##############........", ".#........##########.........."',
      '7120 DATA ".##.........######............", ".##.#.....#########...........", ".####....############........."',
      '7125 DATA "...##...##..######..###.......", "....##.##..########...##......", ".....###..##########...##....."',
      '7130 DATA "..........##########....##....", "...........########.....###...", "............##...##....#####.."',
      '7135 DATA "............##....##...####...", "............##.....##...##....", "............##......##..#....."',
      '7140 DATA "............##.....##.........", "............##....##..........", "............##..###..........."',
      '7145 DATA "...........###...###..........", ".........####.....######......", ".....#######.................."',
      '7150 DATA "..............................", "...#######..........#######...", "......##################......"',
      '7155 DATA ".....####################.....", "....######################....", "...####..##..####..##..####..."',
      '7160 DATA "...####......####......####...", "....######################....", "......##################......"',
      '7165 DATA "........##############........", "..........##########..........", "............######............"',
      '7170 DATA "...........########.....####..", ".........############..#.###..", "......####..######..########.."',
      '7175 DATA "....###....########..#####....", "..######..##########..##......", "..#####...##########.........."',
      '7180 DATA "...........########...........", "...........##....##...........", "..........##......##.........."',
      '7185 DATA "............##....##..........", "........#...##.....##.........", "............##......##........"',
      '7190 DATA "............##.....##.........", "............##....##..........", "............##..###..........."',
      '7195 DATA "...........###...###..........", ".........####.....######......", ".....#######.................."',
      '7200 DATA "..............................", "..............................", "......##............###......."',
      '7205 DATA ".......###........###.........", ".......################.......", "......###################....."',
      '7210 DATA ".....#####################....", "....###..##.###...##.######...", "....###.....###......######..."',
      '7215 DATA ".....#####################....", "......##################......", "........##############........"',
      '7220 DATA "..........##########..........", ".#..........######............", ".##........########..........."',
      '7225 DATA ".##.#....############.........", ".####...##..######..###.......", "...###.##..########...###....."',
      '7230 DATA ".....###..##########....##....", "..........##########....###...", "...........########....#####.."',
      '7235 DATA "...........###...###...####...", "...........##......##...##....", "...........##.......##..#....."',
      '7240 DATA "............##.....##.........", ".............##...##..........", "..............#####..........."',
      '7245 DATA ".............#######..........", "...........####...###.........", ".......#######.....####......."',
      '8000 DATA "###.", "#..#", "#..#", "#..#", "###."',
      '8005 DATA ".##.", "#..#", "####", "#..#", "#..#"',
      '8010 DATA "#..#", "##.#", "#.##", "#..#", "#..#"',
      '8015 DATA ".###", "#...", "#...", "#...", ".###"',
      '8020 DATA "####", ".##.", ".##.", ".##.", "####"',
      '8025 DATA ".###", "#...", "#.##", "#..#", ".###"',
      '8030 DATA "####", "#...", "###.", "#...", "####"',
      '8035 DATA "#..#", "####", "#.##", "#..#", "#..#"',
      '8040 DATA ".##.", "#..#", "#..#", "#..#", ".##."',
      '8100 DATA 0, 1, 0, 2, 0, 1, 0, 2, 0, 3, 0, 4, 3, 0, 4, 0'
    ].join('\n')
  },
  {
    name: 'FRESH80',
    description:
      'FRESH 80 — a brand-new hip-hop show for the demon, built from scratch in ' +
      'Retro80 BASIC: all-new moves (running man, raise the roof, points, a crouch ' +
      'freeze, kicks), an original boom-bap groove, a boombox, and shades. LIST it and remix it!',
    help: {
      about:
        'A fresh hip-hop dance show for our demon, written from scratch in Retro80 BASIC — not a re-sequence of the 1979 moves but all-new sprite poses and an original beat. Because it is our own program, you can LIST it and remix the dance or the music yourself.',
      play: [
        'Press RUN and watch — the title flashes, the beat drops, and the demon dances.',
        'Click or press a key once so the speaker icon turns green (the beat plays through the app audio).',
        'The moves: a bounce/groove, the running man, raise-the-roof, points left and right, a crouch freeze, and a side kick.'
      ],
      hints: [
        'Remix the routine: LIST it — the DATA at 4000-4030 is the choreography, each trio being pose number, sideways sway, and up/down bounce.',
        'The moves live in the DATA at 2000-2720: each pose is a 16-wide by 10-row bitmap drawn at 2x. Edit the # marks to change a pose, or invent your own.',
        'The beat is the PLAY string on line 85 (note notation). Change the notes after MB to write your own track.',
        'Faster dance: lower the PAUSE on line 120. Faster music: raise the T value on line 85.'
      ]
    },
    code: [
      '10 REM ---- FRESH 80 : A HIP HOP SHOW ----',
      '20 DIM HD$(6), FR$(7, 9), FN$(6, 4), MP(15), MX(15), MY(15)',
      '30 FOR R = 0 TO 6 : READ HD$(R) : NEXT R',
      '40 FOR F = 0 TO 7 : FOR R = 0 TO 9 : READ FR$(F, R) : NEXT R : NEXT F',
      '50 FOR T = 0 TO 6 : FOR R = 0 TO 4 : READ FN$(T, R) : NEXT R : NEXT T',
      '55 FOR M = 0 TO 15 : READ MP(M), MX(M), MY(M) : NEXT M',
      '60 KEY$ = "FRESH80" : BX = 48 : BY = 12',
      '70 GOSUB 200 : REM intro - flash the title, then drop the beat',
      '80 REM hip hop groove in A minor',
      '85 PLAY "MB T104 O2 L8 A8 P8 A8 A8 > C8 < A8 P8 G8 A8 P8 A8 A8 E8 G8 P8 A8 F8 P8 F8 F8 > C8 < E8 P8 F8 G8 P8 G8 G8 D8 F8 P8 > C8 < A8 P8 A8 A8 > C8 < A8 P8 G8"',
      '90 FOR P = 1 TO 5',
      '100   FOR M = 0 TO 15',
      '110     CF = MP(M) : DX = MX(M) : DY = MY(M)',
      '120     CLS : GOSUB 300 : GOSUB 500 : PAUSE 150',
      '130   NEXT M',
      '140 NEXT P',
      '150 CF = 0 : DX = 0 : DY = 0 : CLS : GOSUB 300 : GOSUB 500 : END',
      '200 REM ---- intro ----',
      '210 FOR I = 1 TO 6',
      '220   CLS : GOSUB 400 : GOSUB 600',
      '230   IF I - INT(I / 2) * 2 = 1 THEN GOSUB 900',
      '240   PAUSE 170',
      '250 NEXT I',
      '260 RETURN',
      '300 REM ---- full scene ----',
      '310 GOSUB 400 : GOSUB 600 : GOSUB 900 : RETURN',
      '400 FOR X = 4 TO 123 : SET(X, 45) : NEXT X',
      '410 RETURN',
      '500 REM ---- draw dancer (2x) at DX, DY ----',
      '510 FOR R = 0 TO 6 : L$ = HD$(R) : Y = BY + DY + R * 2 : GOSUB 700 : NEXT R',
      '520 FOR R = 0 TO 9 : L$ = FR$(CF, R) : Y = BY + DY + (7 + R) * 2 : GOSUB 700 : NEXT R',
      '530 RETURN',
      '600 REM ---- boombox on the floor ----',
      '610 FOR X = 90 TO 120 : SET(X, 32) : SET(X, 44) : NEXT X',
      '620 FOR Y = 32 TO 44 : SET(90, Y) : SET(120, Y) : NEXT Y',
      '630 FOR X = 99 TO 111 : SET(X, 30) : NEXT X',
      '635 SET(99, 31) : SET(111, 31)',
      '640 FOR A = 0 TO 6 : SET(95 + A, 35) : SET(95 + A, 41) : SET(95, 35 + A) : SET(101, 35 + A) : NEXT A',
      '645 SET(98, 38)',
      '650 FOR A = 0 TO 6 : SET(109 + A, 35) : SET(109 + A, 41) : SET(109, 35 + A) : SET(115, 35 + A) : NEXT A',
      '655 SET(112, 38)',
      '660 FOR X = 104 TO 106 : SET(X, 33) : NEXT X',
      '690 RETURN',
      '700 FOR C = 1 TO LEN(L$)',
      '710   IF MID$(L$, C, 1) <> "#" THEN GOTO 760',
      '720   PX = BX + DX + (C - 1) * 2',
      '730   SET(PX, Y) : SET(PX + 1, Y) : SET(PX, Y + 1) : SET(PX + 1, Y + 1)',
      '760 NEXT C',
      '770 RETURN',
      '900 T$ = "FRESH 80" : TX = 44',
      '910 FOR I = 1 TO LEN(T$)',
      '920   CH$ = MID$(T$, I, 1)',
      '930   IF CH$ = " " THEN TX = TX + 5 : GOTO 995',
      '940   LI = INSTR(KEY$, CH$) - 1',
      '950   FOR R = 0 TO 4 : G$ = FN$(LI, R)',
      '960     FOR C = 1 TO LEN(G$) : IF MID$(G$, C, 1) = "#" THEN SET(TX + C, 1 + R)',
      '970     NEXT C',
      '980   NEXT R',
      '990   TX = TX + 5',
      '995 NEXT I',
      '998 RETURN',
      '1000 DATA "...#......#.....", "...##....##.....", "..############..", "..############.."',
      '1010 DATA "..#...##...#....", "..############..", "....######......"',
      '2000 DATA "...########.....", "..#.######.#....", "....######......", "....######......"',
      '2010 DATA "....##..##......", "....##..##......", "....##..##......", "...###..###....."',
      '2020 DATA "..............." , "..............."',
      '2100 DATA "...########..##.", "..##.######.....", "....######......", "....######......"',
      '2110 DATA "....##..###.....", "....##...##.....", "...##.....##....", "..###......##..."',
      '2120 DATA "..............." , "..............."',
      '2200 DATA ".##..########...", ".....######.##..", "....######......", "....######......"',
      '2210 DATA "...###..##......", "...##...##......", "...##.....##....", "...##......###.."',
      '2220 DATA "..............." , "..............."',
      '2300 DATA "##.########.##..", ".#..######..#...", "....######......", "....######......"',
      '2310 DATA "....##..##......", "....##..##......", "....##..##......", "...###..###....."',
      '2320 DATA "..............." , "..............."',
      '2400 DATA "...########.####", "..#.######......", "....######......", "....######......"',
      '2410 DATA "....##..##......", "...##...##......", "...##....##.....", "..###....###...."',
      '2420 DATA "..............." , "..............."',
      '2500 DATA "####.########...", "......######.#..", "....######......", "....######......"',
      '2510 DATA "....##..##......", "....##...##.....", "....##....##....", "...###....###..."',
      '2520 DATA "..............." , "..............."',
      '2600 DATA "#..########..#..", "..#.######.#....", "...########.....", "..##......##...."',
      '2610 DATA "..##......##....", ".###......###...", "..............." , "..............."',
      '2620 DATA "..............." , "..............."',
      '2700 DATA "...########.....", "..#.######.#....", "....######......", "....######......"',
      '2710 DATA "....##..##......", "....##..###.....", "....##....###...", "...###......####"',
      '2720 DATA "..............." , "..............."',
      '3000 DATA "####", "#...", "###.", "#...", "#..."',
      '3010 DATA "###.", "#..#", "###.", "#.#.", "#..#"',
      '3020 DATA "####", "#...", "###.", "#...", "####"',
      '3030 DATA ".###", "#...", ".##.", "...#", "###."',
      '3040 DATA "#..#", "#..#", "####", "#..#", "#..#"',
      '3050 DATA ".##.", "#..#", ".##.", "#..#", ".##."',
      '3060 DATA ".##.", "#.##", "#.##", "##.#", ".##."',
      '4000 DATA 0, -2, 1, 0, 2, -1, 1, -2, 0, 2, 2, 0',
      '4010 DATA 1, -2, 0, 2, 2, 0, 3, 0, -1, 3, 0, 1',
      '4020 DATA 4, 3, 0, 5, -3, 0, 4, 3, 0, 0, 0, -1',
      '4030 DATA 6, 0, 2, 0, 0, -1, 7, 3, 0, 7, -2, 1'
    ].join('\n')
  },
  {
    name: 'HELLO',
    description: 'The classic first program.',
    code: [
      '10 REM HELLO WORLD',
      '20 PRINT "HELLO, WORLD!"',
      '30 FOR I = 1 TO 3',
      '40   PRINT "RETRO 80 IS READY."',
      '50 NEXT I',
      '60 END'
    ].join('\n')
  },
  {
    name: 'MADLIB',
    description: 'Fill in silly words and get a wacky story! A fun first look at INPUT.',
    code: [
      '10 REM ---- SILLY STORY MAKER (MAD LIB) ----',
      '20 PRINT "LET\'S WRITE A SILLY STORY!"',
      '30 PRINT "TYPE A WORD FOR EACH ONE, THEN PRESS ENTER."',
      '40 PRINT',
      '50 INPUT "AN ANIMAL"; A$',
      '60 INPUT "A SILLY ACTION WORD (LIKE WIGGLE)"; V$',
      '70 INPUT "A PLACE"; P$',
      '80 INPUT "A NUMBER"; N',
      '90 INPUT "YOUR FAVORITE FOOD"; F$',
      '100 PRINT',
      '110 PRINT "ONE DAY A "; A$; " WANTED TO "; V$; "."',
      '120 PRINT "SO IT TRAVELED ALL THE WAY TO "; P$; "!"',
      '130 PRINT "THE TRIP TOOK"; N; "DAYS AND"; N * 2; "SNACKS."',
      '140 PRINT "THE YUMMIEST SNACK OF ALL WAS "; F$; "."',
      '150 PRINT',
      '160 PRINT "THE END. RUN IT AGAIN FOR A NEW STORY!"'
    ].join('\n')
  },
  {
    name: 'MATH',
    description: 'A tiny interactive calculator using INPUT.',
    code: [
      '10 REM SIMPLE MATH',
      '20 INPUT "FIRST NUMBER"; A',
      '30 INPUT "SECOND NUMBER"; B',
      '40 PRINT "SUM     ="; A + B',
      '50 PRINT "DIFF    ="; A - B',
      '60 PRINT "PRODUCT ="; A * B',
      '70 IF B <> 0 THEN PRINT "QUOTIENT ="; A / B',
      '80 PRINT "DONE."'
    ].join('\n')
  },
  {
    name: 'BOX',
    description: 'Draws a frame with the vintage box-drawing characters.',
    code: [
      '10 REM ---- BOX DRAWING DEMO ----',
      '20 REM Box characters live above code 9472 (Unicode).',
      '30 H$ = CHR$(9472) : REM horizontal line',
      '40 V$ = CHR$(9474) : REM vertical line',
      '50 TL$ = CHR$(9484) : TR$ = CHR$(9488)',
      '60 BL$ = CHR$(9492) : BR$ = CHR$(9496)',
      '70 W = 24',
      '80 PRINT TL$; STRING$(W, H$); TR$',
      '90 PRINT V$; SPACE$(W); V$',
      '100 T$ = "    RETRO 80    "',
      '110 P = INT((W - LEN(T$)) / 2)',
      '120 PRINT V$; SPACE$(P); T$; SPACE$(W - P - LEN(T$)); V$',
      '130 PRINT V$; SPACE$(W); V$',
      '140 PRINT BL$; STRING$(W, H$); BR$',
      '150 END'
    ].join('\n')
  },
  {
    name: 'BALL',
    description: 'A round ball bounces inside a drawn box — your first graphics animation.',
    help: {
      about:
        'A little graphics animation: a round ball bounces around inside a box, flipping direction each time it hits a wall. A great first look at SET (turn a pixel on), RESET (turn it off), and PAUSE (to pace the motion).',
      play: ['Press RUN and watch the ball bounce. Press Esc to leave the graphics screen.'],
      hints: [
        'Line 320 draws the ball: it lights every pixel inside an ellipse that is wider than tall (the 4 * J * J), so it looks round — TRS-80 graphics pixels are taller than wide.',
        'Bouncing is just flipping the speed: when the ball reaches a wall, DX or DY becomes its negative (lines 110 and 120).',
        'Make it faster with a smaller PAUSE on line 90, a bigger ball with larger RX / RY on line 30, or a wilder bounce with bigger DX / DY on line 40.'
      ]
    },
    code: [
      '10 REM ---- A BALL BOUNCING INSIDE A BOX ----',
      '20 LFT = 8 : RGT = 119 : TOP = 2 : BOT = 45',
      '30 RX = 6 : RY = 3 : REM ball is wider than tall so it looks round',
      '40 CX = 40 : CY = 22 : DX = 2 : DY = 1',
      '50 CLS',
      '60 FOR F = 1 TO 600',
      '70   GOSUB 500 : REM redraw the box so the walls stay crisp',
      '80   GOSUB 300 : REM draw the ball',
      '90   PAUSE 25',
      '100   GOSUB 400 : REM erase the ball',
      '110   CX = CX + DX : IF CX <= LFT + RX + 1 OR CX >= RGT - RX - 1 THEN DX = -DX',
      '120   CY = CY + DY : IF CY <= TOP + RY + 1 OR CY >= BOT - RY - 1 THEN DY = -DY',
      '130 NEXT F',
      '140 GOSUB 500 : GOSUB 300 : END',
      '300 REM -- draw the ball (an ellipse: wider than tall) --',
      '310 FOR I = -RX TO RX : FOR J = -RY TO RY',
      '320   IF I * I + 4 * J * J <= RX * RX + RX THEN SET(CX + I, CY + J)',
      '330 NEXT J : NEXT I : RETURN',
      '400 REM -- erase the ball --',
      '410 FOR I = -RX TO RX : FOR J = -RY TO RY',
      '420   IF I * I + 4 * J * J <= RX * RX + RX THEN RESET(CX + I, CY + J)',
      '430 NEXT J : NEXT I : RETURN',
      '500 REM -- draw the box --',
      '510 FOR X = LFT TO RGT : SET(X, TOP) : SET(X, BOT) : NEXT X',
      '520 FOR Y = TOP TO BOT : SET(LFT, Y) : SET(RGT, Y) : NEXT Y',
      '530 RETURN'
    ].join('\n')
  },
  {
    name: 'GUESS',
    description: 'A number-guessing game — shows WHILE/WEND and IF.',
    code: [
      '10 REM GUESS THE NUMBER (1-100)',
      '20 N = INT(RND(1) * 100) + 1',
      '30 G = 0 : TRIES = 0',
      '40 WHILE G <> N',
      '50   INPUT "YOUR GUESS"; G',
      '60   TRIES = TRIES + 1',
      '70   IF G < N THEN PRINT "TOO LOW"',
      '80   IF G > N THEN PRINT "TOO HIGH"',
      '90 WEND',
      '100 PRINT "CORRECT! IT TOOK"; TRIES; "TRIES."'
    ].join('\n')
  },
  {
    name: 'TABLE',
    description: 'A multiplication table using nested loops and TAB.',
    code: [
      '10 REM MULTIPLICATION TABLE',
      '20 FOR R = 1 TO 5',
      '30   FOR C = 1 TO 5',
      '40     PRINT TAB(C * 5); R * C;',
      '50   NEXT C',
      '60   PRINT',
      '70 NEXT R'
    ].join('\n')
  },
  {
    name: 'GRAPHICS',
    description: 'Block-graphics demo: a border, crossing diagonals, and a filled box (SET).',
    code: [
      '10 REM ---- GRAPHICS DEMO (128x48 PIXELS) ----',
      '20 CLS',
      '30 REM BORDER',
      '40 FOR X = 0 TO 127 : SET(X, 0) : SET(X, 47) : NEXT X',
      '50 FOR Y = 0 TO 47 : SET(0, Y) : SET(127, Y) : NEXT Y',
      '60 REM CROSSING DIAGONALS',
      '70 FOR X = 0 TO 47 : SET(X, X) : SET(127 - X, X) : NEXT X',
      '80 REM A FILLED BOX IN THE MIDDLE',
      '90 FOR Y = 20 TO 28 : FOR X = 55 TO 73 : SET(X, Y) : NEXT X : NEXT Y',
      '100 END'
    ].join('\n')
  },
  {
    name: 'MUSIC',
    description: 'Plays a tune with PLAY (note notation) and a couple of SOUND beeps. Turn it up!',
    code: [
      '10 REM ---- SOUND AND PLAY DEMO ----',
      '20 PRINT "PLAYING A SCALE..."',
      '30 PLAY "T140 O4 L8 C D E F G A B > C"',
      '40 PAUSE 300',
      '50 PRINT "TWINKLE TWINKLE..."',
      '60 PLAY "T120 O4 L4 C C G G A A G2 F F E E D D C2"',
      '70 PAUSE 300',
      '80 PRINT "TWO BEEPS:"',
      '90 SOUND 880, 120 : SOUND 440, 200',
      '100 PRINT "DONE."',
      '110 END'
    ].join('\n')
  },
  {
    name: 'JAM',
    description: 'Background music (PLAY "MB") while a box bounces — music and animation at once.',
    code: [
      '10 REM ---- BACKGROUND MUSIC + ANIMATION ----',
      '20 CLS',
      '30 REM MB = MUSIC BACKGROUND: STARTS PLAYING AND THE PROGRAM KEEPS GOING',
      '40 PLAY "MB T140 O4 L8 C E G > C < G E C D F A > D < A F D"',
      '50 X = 4 : DX = 2 : Y = 20 : DY = 1',
      '60 FOR F = 1 TO 240',
      '70   GOSUB 200',
      '80   PAUSE 30',
      '90   GOSUB 300',
      '100   X = X + DX : IF X <= 0 OR X >= 118 THEN DX = -DX',
      '110   Y = Y + DY : IF Y <= 0 OR Y >= 40 THEN DY = -DY',
      '120 NEXT F',
      '130 GOSUB 200',
      '140 END',
      '200 FOR I = 0 TO 8 : FOR J = 0 TO 6 : SET(X + I, Y + J) : NEXT J : NEXT I : RETURN',
      '300 FOR I = 0 TO 8 : FOR J = 0 TO 6 : RESET(X + I, Y + J) : NEXT J : NEXT I : RETURN'
    ].join('\n')
  },
  {
    name: 'POKEART',
    description: 'Pokes solid graphic blocks straight into video memory (15360+), like the old days.',
    code: [
      '10 REM ---- POKE GRAPHIC BLOCKS INTO VIDEO RAM ----',
      '20 REM 15360 = TOP-LEFT OF THE SCREEN; 191 = A SOLID 2x3 BLOCK',
      '30 CLS',
      '40 V = 15360',
      '50 REM TOP AND BOTTOM ROWS',
      '60 FOR C = 0 TO 63 : POKE V + C, 191 : POKE V + 15 * 64 + C, 191 : NEXT C',
      '70 REM LEFT AND RIGHT EDGES',
      '80 FOR R = 0 TO 15 : POKE V + R * 64, 191 : POKE V + R * 64 + 63, 191 : NEXT R',
      '90 REM A DIAGONAL OF BLOCKS',
      '100 FOR R = 0 TO 15 : POKE V + R * 64 + R * 4, 191 : NEXT R',
      '110 END'
    ].join('\n')
  },
  {
    name: 'BOUNCE',
    description: 'A box bouncing around the graphics screen — animation via PAUSE.',
    code: [
      '10 REM ---- BOUNCING BOX (ANIMATION) ----',
      '20 X = 4 : DX = 2 : Y = 20 : DY = 1',
      '30 CLS',
      '40 FOR F = 1 TO 400',
      '50   GOSUB 200 : REM draw',
      '60   PAUSE 30',
      '70   GOSUB 300 : REM erase',
      '80   X = X + DX : IF X <= 0 OR X >= 118 THEN DX = -DX',
      '90   Y = Y + DY : IF Y <= 0 OR Y >= 40 THEN DY = -DY',
      '100 NEXT F',
      '110 GOSUB 200 : REM leave it on screen',
      '120 END',
      '200 FOR I = 0 TO 8 : FOR J = 0 TO 6 : SET(X + I, Y + J) : NEXT J : NEXT I : RETURN',
      '300 FOR I = 0 TO 8 : FOR J = 0 TO 6 : RESET(X + I, Y + J) : NEXT J : NEXT I : RETURN'
    ].join('\n')
  },
  {
    name: 'ADVENTURE',
    description:
      'Colossal Cave Adventure — the real quest, based on Crowther & Woods (1977). ' +
      'Six treasures, 350 points, the bird and the snake, a crystal bridge, a knife-throwing ' +
      'dwarf, and a treasure-stealing pirate. XYZZY and PLUGH work. SAVE/LOAD keeps your game.',
    help: {
      about:
        'Colossal Cave Adventure — the game that started the genre, written by Will Crowther in 1976 and expanded by Don Woods in 1977. This is a faithful Retro80 BASIC quest over the canonical geography: 25 locations, six treasures, 350 points. It runs in our own interpreter, so you can LIST it and tinker with the cave itself.',
      play: [
        'Move with N, S, E, W, U, D (or full words). LOOK re-describes a room.',
        'TAKE thing, DROP thing, TAKE ALL, INVENTORY (or I).',
        'OPEN GRATE (you will need something for the lock), LIGHT LAMP, OFF.',
        'Other verbs that matter: WAVE, RELEASE, THROW, EAT, READ the notes on walls.',
        'SCORE shows progress; SAVE and LOAD n (slots 1-3) keep your game across restarts.',
        'Bring all six treasures back to the well house building to win the full 350.'
      ],
      hints: [
        'Collect everything in the building before you head for the cave. The grate is south, past the valley.',
        'Light the lamp before the debris room — two moves in pitch darkness ends in a pit.',
        'The bird is afraid of the black rod. Carry the cage, leave the rod, come back for it.',
        'The fissure is too wide to jump. That rusty-starred rod is magic — WAVE it there.',
        'No way past the snake? Something small and feathered is braver than you are. RELEASE it.',
        'If a dwarf throws an axe at you, pick it up — and THROW AXE next time one threatens you.',
        'Carrying treasure into the maze attracts the pirate. He hides his loot (and yours) with his chest at a dead end — west, west from where you enter.',
        'The magic words XYZZY and PLUGH each work in two special places. The walls tell you one of them.'
      ]
    },
    code: [
      '10 REM ===== COLOSSAL CAVE ADVENTURE =====',
      '12 REM Based on Crowther & Woods (1977). Six treasures, 350 points.',
      '20 DIM RX(25,6) : DIM RD$(25) : DIM OL(13) : DIM ON$(13) : DIM OD$(13)',
      '30 FOR R=1 TO 25 : FOR K=1 TO 6 : READ RX(R,K) : NEXT K : NEXT R',
      '40 FOR R=1 TO 25 : READ RD$(R) : NEXT R',
      '50 FOR I=1 TO 13 : READ ON$(I), OL(I), OD$(I) : NEXT I',
      '60 HERE=1 : LIT=0 : LP=300 : GR=0 : BR=0 : SN=1 : CG=0 : PI=0 : AX=0 : KD=0 : DP=0 : DM=0 : F1=0 : F2=0',
      '70 PRINT "WELCOME TO ADVENTURE!! WOULD YOU LIKE INSTRUCTIONS?"',
      '75 INPUT ":", A$ : IF LEFT$(UCASE$(A$),1)="Y" THEN GOSUB 8000',
      '80 NC=1',
      '100 GOSUB 5000',
      '110 T=0 : FOR I=8 TO 13 : IF OL(I)=3 THEN T=T+1',
      '115 NEXT I',
      '120 IF T=6 THEN 8900',
      '130 INPUT ":", C$',
      '140 IF C$="" THEN 130',
      '150 GOSUB 2000',
      '160 DR=0',
      '170 IF V$="N" OR V$="NORTH" THEN DR=1',
      '180 IF V$="S" OR V$="SOUTH" THEN DR=2',
      '190 IF V$="E" OR V$="EAST" THEN DR=3',
      '200 IF V$="W" OR V$="WEST" THEN DR=4',
      '210 IF V$="U" OR V$="UP" OR V$="CLIMB" THEN DR=5',
      '220 IF V$="D" OR V$="DOWN" THEN DR=6',
      '225 IF V$="GO" OR V$="ENTER" THEN V$=N$ : N$="" : GOTO 170',
      '230 IF DR>0 THEN GOSUB 3000 : IF MOVED=1 THEN 100 ELSE 130',
      '240 IF V$="LOOK" OR V$="L" THEN 100',
      '250 IF V$="TAKE" OR V$="GET" OR V$="GRAB" OR V$="CARRY" THEN GOSUB 4000 : GOTO 110',
      '260 IF V$="DROP" OR V$="LEAVE" THEN GOSUB 4500 : GOTO 110',
      '270 IF V$="INVENTORY" OR V$="INVEN" OR V$="I" THEN GOSUB 4800 : GOTO 130',
      '280 IF V$="OPEN" OR V$="UNLOCK" THEN GOSUB 6000 : GOTO 110',
      '290 IF V$="LIGHT" OR V$="ON" THEN GOSUB 6200 : GOTO 110',
      '300 IF V$="OFF" OR V$="EXTINGUISH" THEN LIT=0 : PRINT "YOUR LAMP IS NOW OFF." : GOTO 130',
      '310 IF V$="WAVE" THEN GOSUB 6300 : GOTO 110',
      '320 IF V$="RELEASE" OR V$="FREE" THEN GOSUB 6400 : GOTO 110',
      '330 IF V$="THROW" THEN GOSUB 6600 : GOTO 110',
      '340 IF V$="EAT" THEN GOSUB 6800 : GOTO 130',
      '350 IF V$="XYZZY" THEN GOSUB 7200 : GOTO 100',
      '360 IF V$="PLUGH" THEN GOSUB 7300 : GOTO 100',
      '370 IF V$="SCORE" THEN GOSUB 8200 : GOTO 130',
      '380 IF V$="HELP" OR V$="?" THEN GOSUB 8000 : GOTO 130',
      '390 IF V$="SAVE" THEN GOSUB 8400 : GOTO 130',
      '400 IF V$="LOAD" OR V$="RESTORE" THEN GOSUB 8500 : GOTO 100',
      '410 IF V$="QUIT" OR V$="Q" THEN GOSUB 8200 : PRINT "COME BACK SOON!" : END',
      '420 PRINT "I DO NOT UNDERSTAND THAT. TRY HELP." : GOTO 130',
      '2000 U$=UCASE$(C$)',
      '2010 P=INSTR(U$," ")',
      '2020 IF P=0 THEN V$=U$ : N$="" : RETURN',
      '2030 V$=LEFT$(U$,P-1) : N$=MID$(U$,P+1)',
      '2040 RETURN',
      '2100 REM -- match noun N$ -> object OB (0 if none) --',
      '2110 OB=0',
      '2120 FOR I=1 TO 13 : IF N$=ON$(I) THEN OB=I',
      '2130 NEXT I',
      '2140 IF N$="KEY" THEN OB=1',
      '2150 IF N$="LANTERN" THEN OB=2',
      '2160 IF N$="NUGGET" THEN OB=8',
      '2170 IF N$="DIAMOND" THEN OB=9',
      '2180 IF N$="BARS" THEN OB=10',
      '2190 IF N$="COIN" THEN OB=12',
      '2200 RETURN',
      '3000 MOVED=0',
      '3010 IF HERE=6 AND DR=6 AND GR=0 THEN PRINT "THE GRATE IS LOCKED. YOU CANNOT GO THROUGH." : RETURN',
      '3020 IF HERE=15 AND DR=4 AND BR=0 THEN PRINT "THE FISSURE IS FAR TOO WIDE TO JUMP." : RETURN',
      '3030 IF HERE=17 AND SN=1 AND (DR=2 OR DR=4 OR DR=6) THEN PRINT "YOU CANNOT GET BY THE SNAKE!" : RETURN',
      '3040 GOSUB 5500 : LT=0 : IF LIT=1 AND OL(2)=0 THEN LT=1',
      '3045 IF DK=1 AND LT=0 THEN GOSUB 3200 : RETURN',
      '3050 NX=RX(HERE,DR)',
      '3060 IF NX=0 THEN PRINT "THERE IS NO WAY TO GO THAT DIRECTION." : RETURN',
      '3070 HERE=NX : MOVED=1 : DM=0',
      '3080 GOSUB 7000',
      '3090 RETURN',
      '3200 REM -- moving in the dark --',
      '3210 DM=DM+1',
      '3220 IF DM=1 THEN PRINT "IT IS NOW PITCH DARK. IF YOU PROCEED YOU WILL LIKELY FALL INTO A PIT." : RETURN',
      '3230 PRINT "YOU FELL INTO A PIT AND BROKE EVERY BONE IN YOUR BODY!"',
      '3240 PRINT "...SUDDENLY, IN A CLOUD OF ORANGE SMOKE, YOU FIND YOURSELF"',
      '3250 PRINT "BACK AT THE BUILDING, SOMEHOW WHOLE AGAIN."',
      '3260 HERE=3 : DM=0 : MOVED=1',
      '3270 RETURN',
      '4000 REM -- TAKE --',
      '4005 IF N$="ALL" THEN 4300',
      '4010 GOSUB 2100',
      '4020 IF OB=0 THEN PRINT "I SEE NO SUCH THING HERE." : RETURN',
      '4030 IF OL(OB)=0 THEN PRINT "YOU ARE ALREADY CARRYING IT!" : RETURN',
      '4040 IF OL(OB)<>HERE THEN PRINT "I SEE NO SUCH THING HERE." : RETURN',
      '4050 IF OB<>5 THEN OL(OB)=0 : PRINT "OK." : RETURN',
      '4060 IF OL(4)=0 THEN PRINT "THE BIRD WAS UNAFRAID WHEN YOU ENTERED, BUT AS YOU APPROACH IT BECOMES" : PRINT "DISTURBED AND YOU CANNOT CATCH IT. PERHAPS THE ROD FRIGHTENS IT." : RETURN',
      '4070 IF OL(3)<>0 THEN PRINT "YOU CAN CATCH THE BIRD, BUT YOU CANNOT CARRY IT." : RETURN',
      '4080 CG=1 : OL(5)=0 : PRINT "YOU CATCH THE BIRD IN THE WICKER CAGE." : RETURN',
      '4300 N=0',
      '4310 FOR I=1 TO 13 : IF OL(I)=HERE AND I<>5 THEN OL(I)=0 : PRINT ON$(I); ": OK." : N=N+1',
      '4320 NEXT I',
      '4330 IF N=0 THEN PRINT "THERE IS NOTHING HERE TO TAKE."',
      '4340 RETURN',
      '4500 REM -- DROP --',
      '4510 GOSUB 2100',
      '4520 IF OB=0 OR OL(OB)<>0 THEN PRINT "YOU ARE NOT CARRYING THAT." : RETURN',
      '4530 IF OB=5 THEN CG=0',
      '4540 OL(OB)=HERE : PRINT "OK." : RETURN',
      '4800 N=0 : PRINT "YOU ARE CURRENTLY HOLDING:"',
      '4810 FOR I=1 TO 13',
      '4812 IF OL(I)<>0 THEN 4820',
      '4814 N=N+1',
      '4816 IF I=5 THEN PRINT "  LITTLE BIRD IN CAGE" ELSE PRINT "  "; ON$(I)',
      '4820 NEXT I',
      '4830 IF N=0 THEN PRINT "  NOTHING AT ALL."',
      '4840 RETURN',
      '5000 IF NC=0 THEN CLS',
      '5010 NC=0',
      '5020 GOSUB 5500',
      '5025 LT=0 : IF LIT=1 AND OL(2)=0 THEN LT=1',
      '5030 IF DK=1 AND LT=0 THEN PRINT "IT IS PITCH DARK. YOU CANNOT SEE A THING." : RETURN',
      '5040 PRINT RD$(HERE)',
      '5050 IF (HERE=6 OR HERE=7) AND GR=0 THEN PRINT "THE GRATE IS LOCKED."',
      '5060 IF (HERE=6 OR HERE=7) AND GR=1 THEN PRINT "THE GRATE STANDS OPEN."',
      '5070 IF (HERE=15 OR HERE=16) AND BR=1 THEN PRINT "A CRYSTAL BRIDGE SPANS THE FISSURE."',
      '5080 IF HERE=17 AND SN=1 THEN PRINT "A HUGE GREEN FIERCE SNAKE BARS THE WAY!"',
      '5090 FOR I=1 TO 13 : IF OL(I)=HERE THEN PRINT OD$(I)',
      '5100 NEXT I',
      '5110 IF DP=1 THEN PRINT "A THREATENING LITTLE DWARF IS IN THE ROOM WITH YOU!"',
      '5120 RETURN',
      '5500 DK=0 : IF HERE>=9 THEN DK=1',
      '5510 RETURN',
      '6000 REM -- OPEN/UNLOCK --',
      '6010 IF N$="CAGE" THEN 6400',
      '6020 IF HERE<>6 AND HERE<>7 THEN PRINT "THERE IS NOTHING HERE TO UNLOCK." : RETURN',
      '6030 IF OL(1)<>0 THEN PRINT "YOU HAVE NO KEYS!" : RETURN',
      '6040 IF GR=1 THEN PRINT "IT IS ALREADY OPEN." : RETURN',
      '6050 GR=1 : PRINT "THE GRATE IS NOW UNLOCKED AND STANDS OPEN." : RETURN',
      '6200 IF OL(2)<>0 THEN PRINT "YOU HAVE NO SOURCE OF LIGHT." : RETURN',
      '6210 IF LP<=0 THEN PRINT "YOUR LAMP HAS RUN OUT OF POWER." : RETURN',
      '6220 LIT=1 : PRINT "YOUR LAMP IS NOW ON." : RETURN',
      '6300 IF OL(4)<>0 THEN PRINT "YOU ARE NOT CARRYING THE ROD." : RETURN',
      '6310 IF HERE<>15 AND HERE<>16 THEN PRINT "NOTHING HAPPENS." : RETURN',
      '6320 IF BR=1 THEN PRINT "THE BRIDGE SHIMMERS BUT REMAINS." : RETURN',
      '6330 BR=1 : PRINT "A CRYSTAL BRIDGE NOW SPANS THE FISSURE!" : RETURN',
      '6400 IF CG=0 OR OL(5)<>0 THEN PRINT "THE CAGE IS EMPTY." : RETURN',
      '6410 IF HERE=17 AND SN=1 THEN SN=0 : CG=0 : OL(5)=17 : PRINT "THE LITTLE BIRD ATTACKS THE GREEN SNAKE, AND IN AN ASTOUNDING FLURRY" : PRINT "DRIVES THE SNAKE AWAY!" : RETURN',
      '6420 CG=0 : OL(5)=HERE : PRINT "THE LITTLE BIRD FLIES FREE, SINGING HAPPILY." : RETURN',
      '6600 IF N$<>"AXE" THEN PRINT "YOU HAVE NOTHING USEFUL TO THROW." : RETURN',
      '6610 IF OL(6)<>0 THEN PRINT "YOU ARE NOT CARRYING THE AXE." : RETURN',
      '6620 IF DP=0 THEN PRINT "THERE IS NOTHING HERE TO ATTACK." : RETURN',
      '6630 KD=1 : DP=0 : OL(6)=HERE',
      '6640 PRINT "YOU KILLED A LITTLE DWARF! THE BODY VANISHES IN A CLOUD OF" : PRINT "GREASY BLACK SMOKE." : RETURN',
      '6800 IF OL(7)<>0 THEN PRINT "YOU HAVE NOTHING TO EAT." : RETURN',
      '6810 OL(7)=-1 : PRINT "THANK YOU, IT WAS DELICIOUS!" : RETURN',
      '7000 REM -- per-move events --',
      '7010 IF HERE>=7 THEN F1=25',
      '7020 IF HERE>=13 THEN F2=25',
      '7030 IF LIT=1 AND OL(2)=0 THEN LP=LP-1',
      '7035 IF LP=40 THEN PRINT "YOUR LAMP IS GETTING DIM. BEST HURRY!"',
      '7040 IF LP=0 AND LIT=1 THEN LIT=0 : PRINT "YOUR LAMP HAS RUN OUT OF POWER!"',
      '7050 IF HERE>=22 AND HERE<=24 AND PI=0 THEN GOSUB 7500',
      '7060 IF HERE<13 OR KD=1 THEN DP=0 : RETURN',
      '7070 IF AX=0 AND RND(1)<.25 THEN AX=1 : OL(6)=HERE : PRINT "A LITTLE DWARF JUST WALKED AROUND A CORNER, SAW YOU, THREW A LITTLE" : PRINT "AXE AT YOU WHICH MISSED, CURSED, AND RAN AWAY." : RETURN',
      '7080 IF AX=1 AND RND(1)<.15 THEN DP=1 : PRINT "A THREATENING LITTLE DWARF COMES OUT OF THE SHADOWS AND THROWS A" : PRINT "KNIFE AT YOU! LUCKILY, IT MISSES." : RETURN',
      '7090 DP=0',
      '7100 RETURN',
      '7200 IF HERE=3 THEN HERE=9 : PRINT ">>FOOF!<<" : RETURN',
      '7210 IF HERE=9 THEN HERE=3 : PRINT ">>FOOF!<<" : RETURN',
      '7220 PRINT "NOTHING HAPPENS." : RETURN',
      '7300 IF HERE=3 THEN HERE=19 : PRINT ">>FOOF!<<" : RETURN',
      '7310 IF HERE=19 THEN HERE=3 : PRINT ">>FOOF!<<" : RETURN',
      '7320 PRINT "NOTHING HAPPENS." : RETURN',
      '7500 T=0 : FOR I=8 TO 13 : IF OL(I)=0 THEN T=1',
      '7510 NEXT I',
      '7520 IF T=0 THEN RETURN',
      '7530 PI=1',
      '7540 FOR I=8 TO 13 : IF OL(I)=0 THEN OL(I)=25',
      '7550 NEXT I',
      '7560 OL(13)=25',
      '7570 PRINT "OUT FROM THE SHADOWS BEHIND YOU POUNCES A BEARDED PIRATE!"',
      '7580 PRINT "HAR HAR, HE CHORTLES. I WILL JUST TAKE ALL THIS BOOTY AND"',
      '7590 PRINT "HIDE IT AWAY WITH ME CHEST DEEP IN THE MAZE!"',
      '7600 PRINT "HE SNATCHES YOUR TREASURE AND VANISHES INTO THE GLOOM."',
      '7610 RETURN',
      '8000 PRINT "I KNOW OF PLACES, ACTIONS, AND THINGS. MOST OF MY VOCABULARY"',
      '8010 PRINT "DESCRIBES PLACES AND IS USED TO MOVE YOU THERE: N S E W U D."',
      '8020 PRINT "TAKE THING, DROP THING, OPEN GRATE, LIGHT LAMP, WAVE ROD,"',
      '8030 PRINT "RELEASE BIRD, THROW AXE, EAT FOOD, INVENTORY, LOOK, SCORE."',
      '8040 PRINT "SOME WORDS ARE MAGIC. SAVE AND LOAD N (SLOTS 1-3) KEEP A GAME."',
      '8050 PRINT "BRING ALL SIX TREASURES BACK TO THE BUILDING TO WIN."',
      '8060 RETURN',
      '8200 SC=F1+F2 : T=0',
      '8210 FOR I=8 TO 13 : IF OL(I)=3 THEN SC=SC+50 : T=T+1',
      '8220 NEXT I',
      '8230 PRINT "YOU HAVE SCORED"; SC; "OUT OF A POSSIBLE 350 POINTS,"',
      '8240 PRINT "WITH"; T; "OF 6 TREASURES SAFELY HOME."',
      '8250 RETURN',
      '8400 INPUT "SAVE TO WHICH SLOT (1-3)"; SL',
      '8410 IF SL<1 OR SL>3 THEN PRINT "NO SUCH SLOT." : RETURN',
      '8420 K$="CAVE"+STR$(SL)',
      '8430 SAVE K$, HERE,LIT,LP,GR,BR,SN,CG,PI,AX,KD,F1,F2,OL(1),OL(2),OL(3),OL(4),OL(5),OL(6),OL(7),OL(8),OL(9),OL(10),OL(11),OL(12),OL(13)',
      '8440 PRINT "GAME SAVED TO SLOT"; SL : RETURN',
      '8500 SL=VAL(N$)',
      '8510 IF SL<1 OR SL>3 THEN PRINT "LOAD WHICH SLOT? TRY: LOAD 1" : RETURN',
      '8520 K$="CAVE"+STR$(SL)',
      '8530 IF NOT EXISTS(K$) THEN PRINT "SLOT"; SL; "IS EMPTY." : RETURN',
      '8540 LOAD K$, HERE,LIT,LP,GR,BR,SN,CG,PI,AX,KD,F1,F2,OL(1),OL(2),OL(3),OL(4),OL(5),OL(6),OL(7),OL(8),OL(9),OL(10),OL(11),OL(12),OL(13)',
      '8550 PRINT "GAME RESTORED FROM SLOT"; SL : RETURN',
      '8900 PRINT',
      '8910 PRINT "ALL SIX TREASURES GLITTER IN THE WELL HOUSE. AN ELF APPEARS,"',
      '8920 PRINT "BOWS DEEPLY, AND DECLARES THE CAVE CLOSED."',
      '8930 GOSUB 8200',
      '8940 PRINT "ADVENTURER, YOU HAVE WON. WELL DONE!"',
      '8950 END',
      '9000 DATA 0,4,3,2,0,0',
      '9010 DATA 0,0,1,0,0,0',
      '9020 DATA 0,0,0,1,0,0',
      '9030 DATA 1,5,0,0,0,0',
      '9040 DATA 4,6,0,0,0,0',
      '9050 DATA 5,0,0,0,0,7',
      '9060 DATA 0,0,0,8,6,0',
      '9070 DATA 0,0,7,9,0,0',
      '9080 DATA 0,0,8,10,0,0',
      '9090 DATA 0,0,9,11,0,0',
      '9100 DATA 0,0,10,12,0,0',
      '9110 DATA 0,0,11,0,0,13',
      '9120 DATA 0,14,12,15,12,17',
      '9130 DATA 13,0,0,0,13,0',
      '9140 DATA 0,0,13,16,0,0',
      '9150 DATA 0,0,15,0,0,0',
      '9160 DATA 13,20,0,21,13,18',
      '9170 DATA 0,19,22,0,17,0',
      '9180 DATA 18,0,0,0,0,0',
      '9190 DATA 17,0,0,0,0,0',
      '9200 DATA 0,0,17,0,0,0',
      '9210 DATA 23,22,18,24,22,23',
      '9220 DATA 22,24,23,23,24,22',
      '9230 DATA 24,23,22,25,23,24',
      '9240 DATA 24,0,0,0,0,0',
      '9300 DATA "YOU ARE STANDING AT THE END OF A ROAD BEFORE A SMALL BRICK BUILDING. AROUND YOU IS A FOREST. A SMALL STREAM FLOWS OUT OF THE BUILDING AND DOWN A GULLY."',
      '9310 DATA "YOU HAVE WALKED UP A HILL, STILL IN THE FOREST. THE ROAD SLOPES BACK DOWN THE OTHER SIDE."',
      '9320 DATA "YOU ARE INSIDE A BUILDING, A WELL HOUSE FOR A LARGE SPRING."',
      '9330 DATA "YOU ARE IN A VALLEY IN THE FOREST BESIDE A STREAM TUMBLING ALONG A ROCKY BED."',
      '9340 DATA "AT YOUR FEET ALL THE WATER OF THE STREAM SPLASHES INTO A 2-INCH SLIT IN THE ROCK."',
      '9350 DATA "YOU ARE IN A 20-FOOT DEPRESSION FLOORED WITH BARE DIRT. SET INTO THE DIRT IS A STRONG STEEL GRATE MOUNTED IN CONCRETE."',
      '9360 DATA "YOU ARE IN A SMALL CHAMBER BENEATH A 3X3 STEEL GRATE TO THE SURFACE. A LOW CRAWL OVER COBBLES LEADS INWARD TO THE WEST."',
      '9370 DATA "YOU ARE CRAWLING OVER COBBLES IN A LOW PASSAGE. THERE IS A DIM LIGHT AT THE EAST END OF THE PASSAGE."',
      '9380 DATA "YOU ARE IN A DEBRIS ROOM FILLED WITH STUFF WASHED IN FROM THE SURFACE. AN AWKWARD CANYON LEADS WEST. A NOTE ON THE WALL SAYS: MAGIC WORD XYZZY."',
      '9390 DATA "YOU ARE IN AN AWKWARD SLOPING EAST/WEST CANYON."',
      '9400 DATA "YOU ARE IN A SPLENDID CHAMBER THIRTY FEET HIGH. THE WALLS ARE FROZEN RIVERS OF ORANGE STONE."',
      '9410 DATA "AT YOUR FEET IS A SMALL PIT BREATHING TRACES OF WHITE MIST. A WEST PASSAGE ENDS HERE."',
      '9420 DATA "YOU ARE AT ONE END OF A VAST HALL STRETCHING FORWARD OUT OF SIGHT TO THE WEST, FILLED WITH WISPS OF WHITE MIST. ROUGH STONE STEPS LEAD UP THE DOME BEHIND YOU. A PASSAGE GOES SOUTH, AND THE HALL CONTINUES DOWN."',
      '9430 DATA "THIS IS A LOW ROOM WITH A CRUDE NOTE ON THE WALL: YOU WONT GET IT UP THE STEPS."',
      '9440 DATA "YOU ARE ON THE EAST BANK OF A FISSURE SLICING CLEAR ACROSS THE HALL. THE MIST IS QUITE THICK HERE."',
      '9450 DATA "YOU ARE ON THE WEST SIDE OF THE FISSURE IN THE HALL OF MISTS."',
      '9460 DATA "YOU ARE IN THE HALL OF THE MOUNTAIN KING, WITH PASSAGES OFF IN ALL DIRECTIONS."',
      '9470 DATA "YOU ARE IN A LOW N/S PASSAGE AT A HOLE IN THE FLOOR. A PASSAGE LEADS EAST INTO A MAZE."',
      '9480 DATA "YOU ARE IN A LARGE ROOM WITH A PASSAGE TO THE NORTH. A LARGE Y2 IS PAINTED ON A ROCK."',
      '9490 DATA "YOU ARE IN THE SOUTH SIDE CHAMBER."',
      '9500 DATA "YOU ARE IN THE WEST SIDE CHAMBER OF THE HALL OF THE MOUNTAIN KING."',
      '9510 DATA "YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE."',
      '9520 DATA "YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE."',
      '9530 DATA "YOU ARE IN A MAZE OF TWISTY LITTLE PASSAGES, ALL ALIKE."',
      '9540 DATA "YOU HAVE REACHED A DEAD END."',
      '9600 DATA "KEYS",3,"  THERE ARE SOME KEYS ON THE GROUND HERE."',
      '9610 DATA "LAMP",3,"  THERE IS A SHINY BRASS LAMP NEARBY."',
      '9620 DATA "CAGE",8,"  THERE IS A SMALL WICKER CAGE DISCARDED NEARBY."',
      '9630 DATA "ROD",9,"  A THREE FOOT BLACK ROD WITH A RUSTY STAR ON AN END LIES NEARBY."',
      '9640 DATA "BIRD",11,"  A CHEERFUL LITTLE BIRD IS SITTING HERE SINGING."',
      '9650 DATA "AXE",-1,"  THERE IS A LITTLE AXE HERE."',
      '9660 DATA "FOOD",3,"  THERE IS FOOD HERE."',
      '9670 DATA "GOLD",14,"  THERE IS A LARGE SPARKLING NUGGET OF GOLD HERE!"',
      '9680 DATA "DIAMONDS",16,"  THERE ARE DIAMONDS HERE!"',
      '9690 DATA "SILVER",18,"  THERE ARE BARS OF SILVER HERE!"',
      '9700 DATA "JEWELRY",20,"  THERE IS PRECIOUS JEWELRY HERE!"',
      '9710 DATA "COINS",21,"  THERE ARE MANY COINS HERE!"',
      '9720 DATA "CHEST",-1,"  THE PIRATES TREASURE CHEST IS HERE!"'
    ].join('\n')
  },
  {
    name: 'HAMURABI',
    description: 'Rule ancient Sumeria for 10 years — the classic resource game (1968).',
    help: {
      about:
        'One of the oldest computer games (1968, as "The Sumer Game"). You are Hamurabi, ruler of ancient Sumeria. Each year you buy or sell land, decide how much grain to feed your people, and how much to plant — then weather, rats, and plague decide your fate. Survive 10 years without too many people starving.',
      play: [
        'Each year, answer three questions with NUMBERS: acres to buy (negative to sell), bushels to feed your people (each needs 20), and acres to plant.',
        'You need 1 bushel of grain to plant every 2 acres, and each person can farm up to 10 acres.',
        'Feed everyone or they starve. If too many starve in one year, you are thrown out of office!'
      ],
      hints: [
        'Keep ~20 bushels per person set aside for food before you buy land or plant.',
        'Buy land when it is cheap; a bigger farm means bigger harvests (if you have people to work it).',
        'Leave a grain reserve — a bad harvest or rats can wipe you out.'
      ]
    },
    code: [
      '10 REM ---- HAMURABI: RULE ANCIENT SUMERIA FOR 10 YEARS ----',
      '20 PRINT "HAMURABI!  RULE ANCIENT SUMERIA FOR A 10-YEAR REIGN."',
      '30 PRINT "EACH YEAR: BUY/SELL LAND, FEED YOUR PEOPLE, PLANT GRAIN."',
      '40 P = 100 : S = 2800 : A = 1000 : TS = 0',
      '50 FOR Z = 1 TO 10',
      '60   Q = INT(RND(1) * 10) + 17',
      '70   PRINT',
      '80   PRINT "YEAR"; Z; "-- YOU RULE"; P; "PEOPLE AND"; A; "ACRES."',
      '90   PRINT "GRAIN IN STORE:"; S; "BUSHELS.  LAND COSTS"; Q; "BUSHELS/ACRE."',
      '100   INPUT "ACRES TO BUY (- TO SELL)"; B',
      '110   IF B * Q > S THEN PRINT "NOT ENOUGH GRAIN." : GOTO 100',
      '120   IF A + B < 0 THEN PRINT "YOU DO NOT OWN THAT MANY ACRES." : GOTO 100',
      '130   A = A + B : S = S - B * Q',
      '140   INPUT "BUSHELS TO FEED YOUR PEOPLE"; F',
      '150   IF F < 0 OR F > S THEN PRINT "YOU HAVE"; S; "BUSHELS." : GOTO 140',
      '160   S = S - F',
      '170   INPUT "ACRES TO PLANT"; C',
      '180   IF C < 0 OR C > A THEN PRINT "YOU OWN"; A; "ACRES." : GOTO 170',
      '190   IF INT(C / 2) > S THEN PRINT "NOT ENOUGH GRAIN FOR SEED." : GOTO 170',
      '200   IF C > 10 * P THEN PRINT "YOUR PEOPLE CAN ONLY FARM"; 10 * P; "ACRES." : GOTO 170',
      '210   S = S - INT(C / 2)',
      '220   Y = INT(RND(1) * 5) + 1 : H = C * Y : S = S + H',
      '230   PRINT "HARVEST:"; H; "BUSHELS ("; Y; "PER ACRE)."',
      '240   E = 0',
      '250   IF RND(1) < 0.4 THEN E = INT(S * RND(1) * 0.3) : S = S - E : PRINT "RATS ATE"; E; "BUSHELS!"',
      '260   FED = INT(F / 20)',
      '270   ST = P - FED : IF ST < 0 THEN ST = 0',
      '280   IF ST > 0 THEN PRINT ST; "PEOPLE STARVED."',
      '290   IF ST > 0.45 * P THEN GOTO 400',
      '300   TS = TS + ST',
      '310   IF FED > P THEN FED = P',
      '320   NB = 0 : IF ST = 0 THEN NB = INT(RND(1) * (S / 200 + A / 200)) + 1',
      '330   IF NB > 0 THEN PRINT NB; "NEW PEOPLE CAME TO SUMERIA."',
      '340   P = FED + NB',
      '350   IF RND(1) < 0.15 THEN P = INT(P / 2) : PRINT "** A PLAGUE STRUCK -- HALF YOUR PEOPLE DIED! **"',
      '360 NEXT Z',
      '370 PRINT : PRINT "YOUR 10-YEAR REIGN HAS ENDED."',
      '380 PRINT "YOU LEAVE"; P; "PEOPLE AND"; A; "ACRES BEHIND."',
      '390 GOTO 420',
      '400 PRINT : PRINT "TOO MANY STARVED IN ONE YEAR -- YOU ARE THROWN OUT OF OFFICE!" : END',
      '420 IF TS < 33 THEN PRINT "A WISE AND WONDERFUL REIGN!"',
      '430 IF TS >= 33 AND TS < 100 THEN PRINT "A RESPECTABLE REIGN."',
      '440 IF TS >= 100 THEN PRINT "MANY SUFFERED. HISTORY JUDGES YOU HARSHLY."',
      '450 END'
    ].join('\n')
  },
  {
    name: 'WUMPUS',
    description: 'Hunt the Wumpus — the 1973 cave-exploring classic. Find it before it finds you.',
    help: {
      about:
        'Gregory Yob’s 1973 classic. You explore a cave of 20 connected rooms hunting a sleeping Wumpus, armed with magic arrows. Bottomless pits and super bats lurk in the dark — but your senses warn you when danger is one room away.',
      play: [
        'Each room connects to three others. You can MOVE to an adjacent room or SHOOT an arrow into one.',
        'Warnings: "you smell the Wumpus" (it is one room away), "you feel a draft" (a pit is near), "you hear bats" (bats are near).',
        'Shoot an arrow into the Wumpus’s room to win. You have 5 arrows. Miss, and the Wumpus may wake and move!'
      ],
      hints: [
        'When you smell the Wumpus, do not move randomly — work out which of the three tunnels is safe.',
        'Super bats whisk you to a random room (maybe into danger). Drafts mean a pit: never move toward one.',
        'Map the rooms as you go; the cave layout never changes during a game.'
      ]
    },
    code: [
      '10 REM ---- HUNT THE WUMPUS ----',
      '20 DIM C(20, 3) : REM each room connects to 3 others',
      '30 FOR R = 1 TO 20 : FOR K = 1 TO 3 : READ C(R, K) : NEXT K : NEXT R',
      '40 DATA 2,5,8, 1,3,10, 2,4,12, 3,5,14, 1,4,6',
      '50 DATA 5,7,15, 6,8,17, 1,7,9, 8,10,18, 2,9,11',
      '60 DATA 10,12,19, 3,11,13, 12,14,20, 4,13,15, 6,14,16',
      '70 DATA 15,17,20, 7,16,18, 9,17,19, 11,18,20, 13,16,19',
      '80 PRINT "HUNT THE WUMPUS!"',
      '90 PRINT "EXPLORE 20 ROOMS. SHOOT THE WUMPUS -- AVOID PITS AND BATS." : PRINT',
      '100 GOSUB 900 : PL = RM',
      '110 GOSUB 900 : IF RM = PL THEN 110',
      '115 WU = RM',
      '120 GOSUB 900 : IF RM = PL OR RM = WU THEN 120',
      '125 P1 = RM',
      '130 GOSUB 900 : IF RM = PL OR RM = WU OR RM = P1 THEN 130',
      '135 P2 = RM',
      '140 GOSUB 900 : IF RM = PL OR RM = WU OR RM = P1 OR RM = P2 THEN 140',
      '145 B1 = RM',
      '150 GOSUB 900 : IF RM = PL OR RM = WU OR RM = P1 OR RM = P2 OR RM = B1 THEN 150',
      '155 B2 = RM',
      '160 AR = 5',
      '190 PRINT',
      '200 PRINT "YOU ARE IN ROOM"; PL',
      '220 FOR K = 1 TO 3 : N = C(PL, K)',
      '230   IF N = WU THEN PRINT "YOU SMELL THE WUMPUS!"',
      '240   IF N = P1 OR N = P2 THEN PRINT "YOU FEEL A DRAFT."',
      '250   IF N = B1 OR N = B2 THEN PRINT "YOU HEAR BATS."',
      '260 NEXT K',
      '270 PRINT "TUNNELS LEAD TO ROOMS"; C(PL, 1); C(PL, 2); C(PL, 3)',
      '280 PRINT "ARROWS LEFT:"; AR',
      '290 INPUT "(M)OVE OR (S)HOOT"; A$',
      '300 A$ = UCASE$(LEFT$(A$, 1))',
      '310 IF A$ = "M" THEN 410',
      '320 IF A$ = "S" THEN 610',
      '330 GOTO 290',
      '410 INPUT "MOVE TO ROOM"; M',
      '420 OK = 0 : FOR K = 1 TO 3 : IF C(PL, K) = M THEN OK = 1',
      '430 NEXT K',
      '440 IF OK = 0 THEN PRINT "THERE IS NO TUNNEL TO THAT ROOM." : GOTO 410',
      '450 PL = M',
      '460 IF PL = WU THEN 800',
      '470 IF PL = P1 OR PL = P2 THEN PRINT "AAAH -- YOU FELL INTO A BOTTOMLESS PIT!" : GOTO 850',
      '480 IF PL = B1 OR PL = B2 THEN PRINT "SUPER BATS GRAB YOU AND DROP YOU ELSEWHERE!" : GOSUB 900 : PL = RM : GOTO 460',
      '490 GOTO 190',
      '610 INPUT "SHOOT INTO WHICH ROOM"; T',
      '620 OK = 0 : FOR K = 1 TO 3 : IF C(PL, K) = T THEN OK = 1',
      '630 NEXT K',
      '640 IF OK = 0 THEN PRINT "YOUR ARROW CLATTERS OFF THE WALL." : GOTO 700',
      '650 IF T = WU THEN PRINT "YOU SHOT THE WUMPUS -- YOU WIN!" : END',
      '660 PRINT "MISSED!"',
      '700 AR = AR - 1',
      '710 IF AR <= 0 THEN PRINT "OUT OF ARROWS!" : GOTO 850',
      '730 IF RND(1) < 0.5 THEN K = INT(RND(1) * 3) + 1 : WU = C(WU, K)',
      '740 IF WU = PL THEN 800',
      '750 GOTO 190',
      '800 PRINT "THE WUMPUS GOBBLES YOU UP! GAME OVER." : END',
      '850 PRINT "GAME OVER." : END',
      '900 RM = INT(RND(1) * 20) + 1 : RETURN'
    ].join('\n')
  }
]
